export const COCKTAIL_GLASSES = [
  "Cocktail glass",
  "Shot glass",
  "Martini Glass",
  "Highball Glass",
  "Highball glass",
  "Collins Glass",
  "Old-fashioned glass",
  "Margarita/Coupette glass",
  "Whiskey sour glass",
  "Champagne Flute",
  "Old-Fashioned glass",
  "Margarita glass",
  "Coupe Glass",
  "Beer pilsner",
  "Punch bowl",
  "Coffee mug",
  "Beer mug",
  "Shot Glass",
  "Punch Bowl",
  "Pint glass",
  "Coffee Mug",
  "Hurricane glass",
  "Collins glass",
  "Pitcher",
  "Beer Glass",
  "Champagne flute",
  "Cocktail Glass",
  "Irish coffee cup",
  "Mason jar",
  "Balloon Glass",
  "Wine Glass",
  "Brandy snifter",
  "Copper Mug",
  "Jar",
  "Nick and Nora Glass",
  "White wine glass",
  "Whiskey Glass",
  "Pousse cafe glass",
  "Cordial glass"
];


